typedef Dijit = {
public function showTooltip(innerHTML:String,aroundNode:Dynamic,?position:Array<String>):Void;
public function hideTooltip(aroundNode:Dynamic):Void;
public function isCollapsed():Bool;
public function getBookmark():Array<Dynamic>;
public function moveToBookmark(bookmark:Dynamic):Void;
public function getFocus(?menu:Dynamic,?openedForWindow:Dynamic):Void;
public function focus(handle:Dynamic):Void;
public function registerIframe(iframe:Dynamic):Void;
public function registerWin(?targetWindow:Dynamic,?effectiveNode:Dynamic):Void;
public function getUniqueId(widgetType:String):String;
public function findWidgets(root:Dynamic):Void;
public function byId(id:Dynamic):Dynamic;
public function byNode(node:Dynamic):Dynamic;
public function getEnclosingWidget(node:Dynamic):Void;
public function isTabNavigable(elem:Dynamic):Bool;
public function getFirstInTabbingOrder(root:Dynamic):Dynamic;
public function getLastInTabbingOrder(root:Dynamic):Dynamic;
public function getViewport():Void;
public function placeOnScreen(node:Dynamic,pos:Dynamic,corners:Array<String>,?padding:Dynamic):Void;
public function placeOnScreenAroundNode(node:Dynamic,aroundNode:Dynamic,aroundCorners:Dynamic,?layoutNode:Dynamic):Void;
public function placeOnScreenAroundRectangle(node:Dynamic,aroundRect:Dynamic,aroundCorners:Dynamic,layoutNode:Dynamic):Void;
public function placeOnScreenAroundElement(node:Dynamic,aroundElement:Dynamic,aroundCorners:Dynamic,layoutNode:Dynamic):Void;
public function scrollIntoView(node:Dynamic):Dynamic;
public function hasWaiRole(elem:Dynamic,role:String):Void;
public function getWaiRole(elem:Dynamic):Void;
public function setWaiRole(elem:Dynamic,role:String):Void;
public function removeWaiRole(elem:Dynamic,role:String):Void;
public function hasWaiState(elem:Dynamic,state:String):Dynamic;
public function getWaiState(elem:Dynamic,state:String):Dynamic;
public function setWaiState(elem:Dynamic,state:String,value:String):Void;
public function removeWaiState(elem:Dynamic,state:String):Void;
public function getDocumentWindow(doc:Dynamic):Dynamic;
public function selectInputText(element:Dynamic,?start:Float,?stop:Float):Void;
public var defaultDuration:Float;
public var registry:Dynamic;
public var placementRegistry:Dynamic;
// public var dijit-all:Dynamic;
public var dijit:Dynamic;
public var demos:Dynamic;
public var robot:Dynamic;
public var robotx:Dynamic;
public function new(prms:Dynamic,?name:String):Void;

}
