package dojox.form;

extern class FileUploader {
function flashMovie():Void;
function new(options:Dynamic):Void;
function log():Void;
function init(options:Dynamic):Void;
function onMouseDown(evt:Dynamic):Void;
function onMouseUp(evt:Dynamic):Void;
function onMouseOver(evt:Dynamic):Void;
function onMouseOut(evt:Dynamic):Void;
function onChange(dataArray:Dynamic):Void;
function onProgress(dataArray:Dynamic):Void;
function onComplete(dataArray:Dynamic):Void;
function onCancel():Void;
function onError(evtObject:Dynamic):Void;
function upload(data:Dynamic):Void;
function setPosition():Void;
function hide():Void;
function show():Void;
function disable(disabled:Bool):Void;
function destroyAll():Void;
function destroy():Void;
function createFlashUploader():Void;
function setFlashVars():Void;
function createHtmlUploader():Void;
function setFlashPosition():Void;
function setHtmlPosition():Void;
function getFakeButtonSize():Void;
var isDebug:Bool;
var devMode:Bool;
var id:String;
var uploadUrl:String;
var button:Dynamic;
var uploadOnChange:Bool;
var selectMultipleFiles:Bool;
var htmlFieldName:String;
var flashFieldName:String;
var fileMask:Dynamic;
var force:String;
var postData:Dynamic;
var swfPath:String;
var minFlashVersion:Float;
var uploaderType:String;
var flashObject:Dynamic;
var flashDiv:Dynamic;
var domNode:Dynamic;

}
