package dojox.form;

extern class Manager extends dijit._Widget {
function _fillContent(source:Dynamic):Void;
function getCachedTemplate(templatePath:String,?templateString:String,alwaysUseString:Dynamic):String;
function registerWidget(widget:Dynamic):Void;
function unregisterWidget(name:String):Void;
function registerWidgetDescendants(widget:Dynamic):Void;
function unregisterWidgetDescendants(widget:Dynamic):Void;
function formWidgetValue(elem:Dynamic,?value:Dynamic):Dynamic;
function formPointValue(elem:Dynamic,?value:Dynamic):Dynamic;
function inspectFormWidgets(inspector:Dynamic,?state:Dynamic,?defaultValue:Dynamic):Dynamic;
function inspectAttachedPoints(inspector:Dynamic,?state:Dynamic,?defaultValue:Dynamic):Dynamic;
function inspect(inspector:Dynamic,?state:Dynamic,?defaultValue:Dynamic):Dynamic;
function registerNode(node:Dynamic):Void;
function unregisterNode(name:String):Void;
function registerNodeDescendants(node:Dynamic):Void;
function unregisterNodeDescendants(node:Dynamic):Void;
function formNodeValue(elem:Dynamic,?value:Dynamic):Dynamic;
function inspectFormNodes(inspector:Dynamic,?state:Dynamic,?defaultValue:Dynamic):Dynamic;
function onReset():Bool;
function reset():Void;
function onSubmit():Bool;
function submit():Void;
function isValid():Void;
function elementValue(name:String,?value:Dynamic):Dynamic;
function gatherFormValues(?names:Dynamic):Dynamic;
function setFormValues(values:Dynamic):Void;
function gatherEnableState(?names:Dynamic):Dynamic;
function enable(?state:Dynamic,defaultState:Bool):Dynamic;
function disable(?state:Dynamic):Dynamic;
function gatherDisplayState(?names:Dynamic):Dynamic;
function show(?state:Dynamic,?defaultState:Bool):Dynamic;
function hide(?state:Dynamic):Dynamic;
function gatherClassState(className:String,?names:Dynamic):Dynamic;
function addClass(className:String,?names:Dynamic):Dynamic;
function removeClass(className:String,?names:Dynamic):Dynamic;
var templateString:String;
var templatePath:String;
var widgetsInTemplate:Bool;
var watch:Bool;
var name:String;
var action:String;
var method:String;
var encType:String;
// var accept-charset:String;
var accept:String;
var target:String;

}
